###############################################################
#                   Authelia configuration                    #
###############################################################

host: 0.0.0.0
port: 9091
log_level: info
log_file_path: /var/lib/authelia/authelia.log
jwt_secret: my_very_important_secret
default_redirection_url: https://example.com

totp:
  issuer: authelia.com

authentication_backend:
  disable_reset_password: true
  file:
    path: /config/users_database.yml
    password:
      algorithm: sha512
      parallelism: 2
      memory: 256

access_control:
  default_policy: one_factor

session:
  name: authelia_session
  secret: authelia_unsecure_session_secret
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: example.com # Should match whatever your root protected domain is

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  local:
    path: /var/lib/authelia/db.sqlite3

notifier:
  # filesystem:
  #   filename: /var/lib/authelia/notification.txt
  smtp:
    username: 
    password: 
    host: mailhog
    port: 1025
    sender: admin@example.com
    subject: "[Authelia] {title}"
    disable_require_tls: true
    disable_verify_cert: true

