# the default admin details admin@admin.com with a password of password
version: '3.5'
services:
  bookstack:
    image: linuxserver/bookstack:latest
    container_name: bookstack
    restart: unless-stopped
    # user: ${UID}:${GID}
    depends_on:
      - bookstack_db
    hostname: bookstack
    networks:
      - traefik
      - bookstack
    # ports:
    #   - 2080:8080
    # dns:
    #   - 172.31.254.254
    env_file:
      - ./env-global.env
    environment:
      - APP_URL=https://bookstack.${DOMAINNAME}
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=bookstack
      - DB_DATABASE=bookstackapp
      - MAIL_DRIVER=smtp
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${VOLUMEPATH}/bookstack:/config
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_network
      - traefik.http.routers.bookstack.entrypoints=websecure
      - traefik.http.routers.bookstack.tls.certresolver=letsencrypt
      - traefik.http.routers.bookstack.rule=Host(`bookstack.${DOMAINNAME}`)
      - traefik.http.services.bookstack.loadbalancer.server.port=80
      # - traefik.http.routers.bookstack.middlewares=authelia@docker

  bookstack_db:
    container_name: bookstack_db
    image: linuxserver/mariadb
    restart: unless-stopped
    # user: ${UID}:${GID}
    hostname: bookstack_db
    networks:
      - bookstack
    env_file:
      - ./env-global.env
    environment:
      - MYSQL_ROOT_PASSWORD=bookstack
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=bookstack
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${VOLUMEPATH}/bookstack_db:/config
    labels:
      - traefik.enable=false

networks:
  traefik:
    external:
      name: traefik_network
  bookstack:
    internal: true


